%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/mbexegc2/Downloads/Volt v image avg 3set.xlsm
%    Worksheet: DL
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/12 08:45:48

%% Import the data
[~, ~, raw] = xlsread(datafile,'DL');
raw = raw(2:4917,1:2);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
lf_time = data(:,1);
lf_v = data(:,2);

%% Clear temporary variables
clearvars data raw R;